USE inventory;

CREATE TEMPORARY TABLE seq_1m AS
SELECT (@rownum := @rownum + 1) AS n
FROM (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e
CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) f
CROSS JOIN (SELECT @rownum := 0) r
LIMIT 600000;

INSERT INTO customers (first_name, last_name, email, created_at)
SELECT
    CONCAT('First', n),
    CONCAT('Last', n),
    CONCAT('customer', n, '@example.com'),
    TIMESTAMPADD(MINUTE, n, '2024-01-01 00:00:00')
FROM seq_1m
WHERE n <= 100000;

INSERT INTO products (name, description, price)
SELECT
    CONCAT('Product ', n),
    CONCAT('Description for product ', n),
    ROUND(5 + (n % 5000) / 10, 2)
FROM seq_1m
WHERE n <= 50000;

INSERT INTO orders (customer_id, product_id, quantity, order_date)
SELECT
    ((n - 1) % 100000) + 1,
    ((n - 1) % 50000) + 1,
    ((n - 1) % 5) + 1,
    TIMESTAMPADD(SECOND, n, '2024-02-01 00:00:00')
FROM seq_1m
WHERE n <= 400000;

DROP TEMPORARY TABLE IF EXISTS seq_1m;
