CREATE USER IF NOT EXISTS 'debezium_user'@'%' IDENTIFIED BY 'debezium_pw';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'debezium_user'@'%';
GRANT ALL PRIVILEGES ON inventory.* TO 'debezium_user'@'%';
FLUSH PRIVILEGES;
